name: Dotnet Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6', '7', '8' ]

    name: Dotnet ${{ matrix.dotnet }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Install dependencies
      run: dotnet restore OpenGSQ
    - name: Build
      run: dotnet build OpenGSQ --no-restore
    # - name: Test
    #   run: dotnet test OpenGSQ --no-build --verbosity normal
