name: Publish Dotnet Package (GPR)

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7
        source-url: https://nuget.pkg.github.com/OpenGSQ/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build
      run: dotnet build OpenGSQ -c Release
    - name: Create the package
      run: dotnet pack OpenGSQ -c Release
    - name: Publish the package to GPR
      run: dotnet nuget push OpenGSQ/bin/Release/*.nupkg
