name: Dotnet Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
      - name: Install dependencies
        run: dotnet restore OpenGSQ
      - name: Build
        run: dotnet build OpenGSQ --no-restore
    # - name: Test
    #   run: dotnet test OpenGSQ --no-build --verbosity normal
