name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '2.0.x', '3.0.x', '5.0.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore dependencies
      run: dotnet restore OpenGSQ
    - name: Build
      run: dotnet build OpenGSQ --no-restore
    - name: Test
      run: dotnet test OpenGSQ --no-build --verbosity normal
